// lib/ringPresets.js
// One config object per page. Add a new page's ring by adding one entry
// here — no new SVG markup required, OrbitalRing.jsx does the drawing.
//
// Shape of each entry (for reference, since there's no TS to enforce it):
// {
//   ticks: number,
//   rings: number[],
//   dash: string,          // stroke-dasharray for the rotating dashed ring
//   dashRing: number,      // radius of that dashed ring
//   arcColor: string,
//   arcStart: number,      // degrees
//   arcSweep: number,      // degrees
//   spinClass: "spin" | "spin-s" | "spin-l",
//   spinrClass?: "spinr" | "spinr-s" | "spinr-l",
// }

import { RING_RADII_2, RING_RADII_3 } from "./ringMath";

export const ringPresets = {
  home: {
    ticks: 8,
    rings: RING_RADII_3,
    dash: "6 44",
    dashRing: 150,
    arcColor: "#FFB020",
    arcStart: 0,
    arcSweep: 52,
    spinClass: "spin",
    spinrClass: "spinr",
  },
  about: {
    ticks: 10,
    rings: RING_RADII_3,
    dash: "5 40",
    dashRing: 150,
    arcColor: "#FFB020",
    arcStart: 10,
    arcSweep: 55,
    spinClass: "spin-l",
    spinrClass: "spinr",
  },
  "web-development": {
    ticks: 8,
    rings: RING_RADII_2,
    dash: "8 34",
    dashRing: 150,
    arcColor: "#5CE0C4",
    arcStart: 200,
    arcSweep: 70,
    spinClass: "spin",
    spinrClass: "spinr-s",
  },
  "uiux-design": {
    ticks: 12,
    rings: RING_RADII_3,
    dash: "4 26",
    dashRing: 150,
    arcColor: "#FFB020",
    arcStart: 120,
    arcSweep: 100,
    spinClass: "spin-s",
    spinrClass: "spinr",
  },
  "mobile-app-development": {
    ticks: 6,
    rings: RING_RADII_2,
    dash: "10 30",
    dashRing: 150,
    arcColor: "#5CE0C4",
    arcStart: 280,
    arcSweep: 45,
    spinClass: "spin-s",
    spinrClass: "spinr-l",
  },
  "iot-solutions": {
    ticks: 14,
    rings: RING_RADII_3,
    dash: "3 18",
    dashRing: 150,
    arcColor: "#FFB020",
    arcStart: 40,
    arcSweep: 65,
    spinClass: "spin-l",
    spinrClass: "spinr-s",
  },
  "digital-transformation": {
    ticks: 8,
    rings: RING_RADII_2,
    dash: "6 44",
    dashRing: 150,
    arcColor: "#5CE0C4",
    arcStart: 160,
    arcSweep: 90,
    spinClass: "spin",
    spinrClass: "spinr",
  },
  "digital-marketing": {
    ticks: 10,
    rings: RING_RADII_3,
    dash: "7 24",
    dashRing: 150,
    arcColor: "#FFB020",
    arcStart: 230,
    arcSweep: 50,
    spinClass: "spin",
    spinrClass: "spinr-l",
  },
  portfolio: {
    ticks: 12,
    rings: RING_RADII_2,
    dash: "5 20",
    dashRing: 150,
    arcColor: "#5CE0C4",
    arcStart: 300,
    arcSweep: 80,
    spinClass: "spin-s",
    spinrClass: "spinr",
  },
  career: {
    ticks: 6,
    rings: RING_RADII_3,
    dash: "9 36",
    dashRing: 150,
    arcColor: "#FFB020",
    arcStart: 60,
    arcSweep: 100,
    spinClass: "spin-l",
    spinrClass: "spinr-l",
  },
  blog: {
    ticks: 16,
    rings: RING_RADII_2,
    dash: "2 12",
    dashRing: 150,
    arcColor: "#5CE0C4",
    arcStart: 340,
    arcSweep: 40,
    spinClass: "spin",
    spinrClass: "spinr-s",
  },
  contact: {
    ticks: 8,
    rings: RING_RADII_3,
    dash: "6 30",
    dashRing: 150,
    arcColor: "#FFB020",
    arcStart: 100,
    arcSweep: 55,
    spinClass: "spin-s",
    spinrClass: "spinr-l",
  },
  "privacy-policy": {
    ticks: 4,
    rings: RING_RADII_2,
    dash: "4 50",
    dashRing: 150,
    arcColor: "#5CE0C4",
    arcStart: 15,
    arcSweep: 30,
    spinClass: "spin-l",
    // no spinrClass — the calmest page gets only one rotating ring
  },
};
